name: "build-devel-rpm"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'jailkit'

      - name: Install dependencies
        run: |-
          sudo apt-get -y update
          sudo apt-get -y install rpm perl build-essential gnupg curl libconfig-inifiles-perl libtest-strict-perl
          curl -O https://raw.githubusercontent.com/webmin/webmin/master/mod_def_list.txt
          curl -O https://raw.githubusercontent.com/webmin/webmin/master/makemodulerpm.pl
      - name: Run tests
        run: |-
          cd jailkit
          prove
      - name: Build package
        env:
          APTLY_USER: ${{ secrets.APTLY_USER }}
          APTLY_PASSWD: ${{ secrets.APTLY_PASSWD }}
        run: |-
          jailkit/build-devel-rpm.sh
