name: "build-devel-deb"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'jailkit'

      - name: Install dependencies
        run: |-
          sudo apt-get -y update
          sudo apt-get -y install perl build-essential gnupg pbuilder curl libconfig-inifiles-perl libtest-strict-perl
          curl -O https://raw.githubusercontent.com/webmin/webmin/master/mod_def_list.txt
          curl -O https://raw.githubusercontent.com/webmin/webmin/master/makemoduledeb.pl
      - name: Run tests
        run: |-
          cd jailkit
          prove
      - name: Build package
        run: |-
          mkdir tmp
          perl makemoduledeb.pl --deb-depends --licence 'GPLv3' --email 'joe@virtualmin.com' --allow-overwrite --target-dir tmp jailkit
